# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Answer.destroy_all
Question.destroy_all
Favorite.destroy_all
UserSurveyJoiner.destroy_all
Survey.destroy_all
User.destroy_all

user1 = User.create(username: "Eli", password: "111", image: "https://media-exp1.licdn.com/dms/image/C5103AQFFZLdeCh71OQ/profile-displayphoto-shrink_200_200/0?e=1588204800&v=beta&t=w_9zy0BhYrW0crdEinLrvG_DTsSeWMKCFA4_2geS_b4", interest: "Software Engineering, Investing, Music, & Sports", email: "elirkantor@gmail.com")
user2 = User.create(username: "Lebron", password: "222", image: "https://ssref.net/scripts/image_resize.cgi?min=200&url=https://d2cwpp38twqe55.cloudfront.net/req/202002141/images/players/jamesle01.jpg", interest: "Basketball.  Winning.  Tacos.", email: "Undisclosed")
user3 = User.create(username: "Erin Burnett", password: "3", image: "https://marriedbio.com/uploads/2017/03/Erin-Burnett.jpg", interest: "Politics & TV", email: "http://outfront.blogs.cnn.com/")
user4 = User.create(username: "Billie Eilish", password: "4", image: "https://cdn.cnn.com/cnnnext/dam/assets/200127015635-billie-eilish-large-169.jpg", interest: "Music and stuff", email: "https://www.billieeilish.com/")
survey1 = Survey.create(name: "Software Engineering", user: user1)
survey2 = Survey.create(name: "Favorite Dumbo Lunch Spot", user: user1)
survey3 = Survey.create(name: "All Things NBA", user: user2)
survey4 = Survey.create(name: "Politics 2020", user: user3)
survey5 = Survey.create(name: "Mostly Music", user: user4)
joiner1 = UserSurveyJoiner.create(user: user1, survey: survey2)
favorite1 = Favorite.create(user:user1, survey: survey1)
favorite2 = Favorite.create(user:user1, survey: survey3)
question1 = Question.create(content: "What is your favorite programming language?", survey: survey1)
question2 = Question.create(content: "What is your favorite Javascript framework?", survey: survey1)
question4 = Question.create(content: "Where is your favorite place to get lunch?", survey: survey2)
question3 = Question.create(content: "Who is your favorite NBA Team?", survey: survey3)
question5 = Question.create(content: "Who is your favorite US President?", survey: survey4)
question6 = Question.create(content: "Who do you plan to vote for in the 2020 presidential election?", survey: survey4)
question7 = Question.create(content: "What political party do you most identify with?", survey: survey4)
question8 = Question.create(content: "Who is the best player in the NBA right now?", survey: survey3)
question9 = Question.create(content: "Who is your favorite NBA player of all-time?", survey: survey3)
question10 = Question.create(content: "Who do you think will will the NBA championship this year?", survey: survey3)
question11 = Question.create(content: "What city hosts the best live music concerts?", survey: survey5)
answer1 = Answer.create(content: "Javascript", total: 50, question: question1)
answer2 = Answer.create(content: "Python", total: 25, question: question1)
answer3 = Answer.create(content: "Ruby", total: 40, question: question1)
answer4 = Answer.create(content: "PHP", total: 10, question: question1)
answer5 = Answer.create(content: "C++", total: 5, question: question1)
answer6 = Answer.create(content: "React JS", total: 75, question: question2)
answer7 = Answer.create(content: "Node.js", total: 20, question: question2)
answer8 = Answer.create(content: "Angular", total: 50, question: question2)
answer9 = Answer.create(content: "Vue.js", total: 40, question: question2)
answer10 = Answer.create(content: "jQuery", total: 30, question: question2)
answer11 = Answer.create(content: "New York Knicks", total: 0, question: question3)
answer12 = Answer.create(content: "Brooklyn Nets", total: 0, question: question3)
answer13 = Answer.create(content: "Golden State Warriors", total: 0, question: question3)
answer14 = Answer.create(content: "New Orleans Pelicans", total: 0, question: question3)
answer15 = Answer.create(content: "Other", total: 0, question: question3)
answer16 = Answer.create(content: "Wholesome Farms", total: 5, question: question4)
answer17 = Answer.create(content: "Bread & Spread", total: 10, question: question4)
answer18 = Answer.create(content: "Bridge Fresh", total: 7, question: question4)
answer19 = Answer.create(content: "Halal Cart", total: 20, question: question4)
answer20 = Answer.create(content: "Other", total: 6, question: question4)
answer21 = Answer.create(content: "Barack Obama", total: 0, question: question5)
answer22 = Answer.create(content: "George H.W. Bush", total: 0, question: question5)
answer23 = Answer.create(content: "Bill Clinton", total: 0, question: question5)
answer24 = Answer.create(content: "George W. Bush", total: 0, question: question5)
answer25 = Answer.create(content: "Ronald Reagan", total: 0, question: question5)
answer26 = Answer.create(content: "Joe Biden", total: 0, question: question6)
answer27 = Answer.create(content: "Bernie Sanders", total: 0, question: question6)
answer28 = Answer.create(content: "Donald Trump", total: 0, question: question6)
answer29 = Answer.create(content: "Elizabeth Warren", total: 0, question: question6)
answer30 = Answer.create(content: "I don't plan to vote", total: 0, question: question6)
answer31 = Answer.create(content: "Democrat", total: 0, question: question7)
answer32 = Answer.create(content: "Republican", total: 0, question: question7)
answer33 = Answer.create(content: "Independent", total: 0, question: question7)
answer34 = Answer.create(content: "Socialist", total: 0, question: question7)
answer35 = Answer.create(content: "Other", total: 0, question: question7)
answer36 = Answer.create(content: "Lebron James", total: 0, question: question8)
answer37 = Answer.create(content: "Giannis Antetokounmpo", total: 0, question: question8)
answer38 = Answer.create(content: "James Harden", total: 0, question: question8)
answer39 = Answer.create(content: "Kawhi Leonard", total: 0, question: question8)
answer40 = Answer.create(content: "Kevin Durant", total: 0, question: question8)
answer41 = Answer.create(content: "Michael Jordan", total: 0, question: question9)
answer42 = Answer.create(content: "Oscar Robertson", total: 0, question: question9)
answer43 = Answer.create(content: "Bill Russell", total: 0, question: question9)
answer44 = Answer.create(content: "Larry Bird", total: 0, question: question9)
answer45 = Answer.create(content: "Tim Duncan", total: 0, question: question9)
answer46 = Answer.create(content: "LA Lakers", total: 0, question: question10)
answer47 = Answer.create(content: "LA Clippers", total: 0, question: question10)
answer48 = Answer.create(content: "Milwaukee Bucks", total: 0, question: question10)
answer49 = Answer.create(content: "Boston Celtics", total: 0, question: question10)
answer50 = Answer.create(content: "Dallas Mavericks", total: 0, question: question10)
answer51 = Answer.create(content: "New York City", total: 400, question: question11)
answer52 = Answer.create(content: "Los Angeles", total: 300, question: question11)
answer53 = Answer.create(content: "New Orleans", total: 1000, question: question11)
answer54 = Answer.create(content: "Ibiza", total: 700, question: question11)
answer55 = Answer.create(content: "Other", total: 4, question: question11)
